extern crate self as fixed_record;

pub mod error;
pub mod io;
pub mod traits;
pub mod types;

pub use fixed_record_macros::fixed_record;

pub use error::Error;
pub use io::{Reader, Writer};
pub use traits::FixedRecord;
pub use types::Fixed;

pub mod prelude {
    pub use crate::fixed_record;
    pub use crate::{Error, Fixed, FixedRecord, Reader, Writer};
}

/// Documentation examples for APIs generated by [`macro@fixed_record`].
/// [`macro@fixed_record`] が生成する API を rustdoc で確認するためのサンプルです。
#[cfg(doc)]
pub mod doc_examples {
    use crate::prelude::*;

    /// Test record used to document the generated fixed-record API.
    /// 生成される fixed-record API のドキュメント用テストレコードです。
    #[fixed_record]
    pub struct TestRecord {
        /// Name field used by generated API tests.
        /// 生成 API テストで使う名前フィールドです。
        name: Fixed<10>,
        /// Code field used by generated API tests.
        /// 生成 API テストで使うコードフィールドです。
        code: Fixed<5>,
        /// Amount field used by generated API tests.
        /// 生成 API テストで使う金額フィールドです。
        amount: Fixed<8>,
    }
}
