[package]
name = "fixed-record"
version = "0.1.0"
edition = "2024"

[features]
default = ["list"]
list = ["fixed-record-macros/list"]
unchecked = ["fixed-record-macros/unchecked"]

[dependencies]
# ローカルパスでマクロクレートを指定
fixed-record-macros = { path = "../fixed-record-macros", default-features = false }

[dev-dependencies]
trybuild = "1.0"
